### ISSUE TITLE
Please don't force capitalisation in admin CSS

### ISSUE THREAD

**Issue by Toutouwai** [processwire/processwire-requests#152]
### Short description of the enhancement

AdminThemeUikit has CSS rules:

```css
.uk-button {
    text-transform: capitalize;
}

.ui-button,.ui-button.ui-state-default,.ui-button.ui-state-hover {
    text-transform: capitalize;
}
```

If a developer wants their button text in title case they'll enter it in title case. The decision shouldn't be taken out of their hands by the admin CSS.

On the topic, I'd love it if the use of letter case could be reviewed across ProcessWire. At the moment there is a lot of inconsistency. There's an old issue about this: https://github.com/ryancramerdesign/ProcessWire/issues/1512

In my opinion, title case looks dated and gets very awkward for longer headings. There are [pros and cons](https://medium.com/@jsaito/making-a-case-for-letter-case-19d09f653c98) either way, but I come down firmly in favour of sentence case. My perception is that the majority of tasteful, modern layouts/interfaces use sentence case in headings and labels. Random examples:
https://github.com/features
https://www.dropbox.com/business/tour
https://stripe.com/about

**Comment by apeisa** [comment]
Just a heads up for this. Capitalize might work in English, but for example in Finnish it is just plain wrong to use it (only names are capitalized - even in headlines, button labels etc).

**Comment by BernhardBaumrock** [comment]
Same for german! +1

**Comment by jmartsch** [comment]
Now there are two issues for this problem. This issue is in the ideas repo, and I think will maybe get some attention in some years. As I not see this as an idea but rather than an error, maybe pls vote for the issue https://github.com/processwire/processwire-issues/issues/887 and close this one here, although this one is a little bit older.

**Comment by jmartsch** [comment]
@Toutouwai This request can be closed, as it is fixed now. See https://github.com/processwire/processwire/commit/6d8d504d44054a010c351f5741e181bc4952edd8

**Comment by Toutouwai** [comment]
I'll leave it open. As per the description, this request is about giving module developers control over the casing in button labels, and about modern English language style. The referenced commit doesn't resolve these things.

**Comment by jmartsch** [comment]
Bump for your consideration @ryancramerdesign
